// Command generateagl generates Go mappings from the checked-in Adobe lists.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
	"unicode/utf8"
)

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	license, err := os.ReadFile("data/agl/LICENSE.md")
	if err != nil {
		return err
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	output.WriteString("// Copyright 2002-2019 Adobe (http://www.adobe.com/).\n")
	output.WriteString("// Source: adobe-type-tools/agl-aglfn at 4036a9ca80a62f64f9de4f7321a9a045ad0ecfd6.\n")
	for _, line := range strings.Split(strings.TrimSpace(string(license)), "\n") {
		fmt.Fprintf(&output, "// %s\n", line)
	}
	output.WriteString("\npackage font\n")
	for _, list := range []struct{ file, variable string }{
		{"glyphlist.txt", "glyphNameToUnicode"}, {"zapfdingbats.txt", "zapfGlyphNameToUnicode"},
	} {
		data, err := os.ReadFile("data/agl/" + list.file)
		if err != nil {
			return err
		}
		fmt.Fprintf(&output, "\nvar %s = map[string]string{\n", list.variable)
		scanner := bufio.NewScanner(bytes.NewReader(data))
		seen := map[string]bool{}
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			fields := strings.Split(line, ";")
			if len(fields) != 2 || seen[fields[0]] {
				return fmt.Errorf("invalid or duplicate entry: %s", line)
			}
			seen[fields[0]] = true
			var value strings.Builder
			for _, code := range strings.Fields(fields[1]) {
				n, err := strconv.ParseUint(code, 16, 32)
				if err != nil || n > utf8.MaxRune || !utf8.ValidRune(rune(n)) {
					return fmt.Errorf("invalid Unicode scalar: %s", code)
				}
				value.WriteRune(rune(n))
			}
			if value.Len() == 0 {
				return fmt.Errorf("empty mapping: %s", line)
			}
			fmt.Fprintf(&output, "%q: %q,\n", fields[0], value.String())
		}
		if err := scanner.Err(); err != nil {
			return err
		}
		output.WriteString("}\n")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile("glyph_data_generated.go", formatted, 0644)
}
